import { pairContext } from './pairContext.js';
export function render(ctx){
 const {data:d,safe:s}=ctx;if(!d)return '<h1>After your date</h1><p>Loading…</p>';
 const agreement=(kind,title)=>`<button class="secondary" data-agreement="${kind}">${d.agreements?.[kind]?.mine?'✓ Your agreement completed — review':title}</button><p class="hint">Partner agreement: ${d.agreements?.[kind]?.partner?'completed':'not yet completed'}</p>`;
 return `<h1>After your date</h1><button class="secondary" id="after-refresh">Refresh partner progress</button>${pairContext(ctx)}<p>Every request is optional. Declining is free and is not shown as a rejection to the requester. No details are shared automatically.</p>
 <section class="card"><h2>Contact sharing</h2>${agreement('contact_share','Review contact-sharing agreement')}<form id="contact-request"><label>Request a channel<select name="channel">${(d.contact_channels||[]).map(c=>`<option>${s(c)}</option>`).join('')}</select></label><button class="secondary">Send request</button></form>
 ${(d.contact_requests||[]).map(r=>`<div class="clause"><h3>${s(r.channel)} · ${r.sent_by_me?'Your request':'Request to you'}</h3><p>${s(r.status)}</p>${r.contact?`<p>Shared contact: <strong>${s(r.contact)}</strong></p>`:''}${!r.sent_by_me&&r.status==='pending'?`<form data-contact="${s(r.id)}">${['instagram','linkedin','facebook','snapchat'].includes(r.channel)?'<label>Your handle or profile URL (shared only if you accept)<input name="contact_value" maxlength="200"></label>':''}<button class="secondary" name="response" value="accepted" ${d.agreements?.contact_share?.mine?'':'disabled'}>Accept sharing</button><button class="secondary" name="response" value="declined">Decline</button><button class="secondary" name="response" value="ignored">Not now</button></form>`:''}${r.status==='accepted'&&!r.contact?'<p class="hint">Contact release requires both contact-sharing agreements.</p>':''}</div>`).join('')}</section>
 <section class="card"><h2>Home visit — optional</h2><p>First complete both contact-sharing agreements, then your home-visit agreement. A visit never implies consent to intimacy.</p>${agreement('home_invite','Review home-visit agreement')}<form id="home-invite"><label>Proposed local date and time<input type="datetime-local" name="when" required></label><label>Expectations<select name="flag">${(d.expectation_flags||[]).map(f=>`<option value="${s(f)}">${s(d.expectation_labels?.[f]||f)}</option>`).join('')}</select></label><button class="secondary" ${d.agreements?.contact_share?.mine&&d.agreements?.contact_share?.partner&&d.agreements?.home_invite?.mine?'':'disabled'}>Propose visit</button></form>
 <p>${s(d.invite_acknowledgement)}</p><p class="hint">Share your plans with a trusted contact yourself; this app does not send a safety notification.</p>
 ${(d.home_invites||[]).map(r=>`<div class="clause"><h3>${s(r.proposed_datetime)}</h3><p>${s(d.expectation_labels?.[r.expectation_flag]||r.expectation_flag)}</p><p>${s(r.status)} · ${r.both_acknowledged?'✓ Both acknowledged':r.my_acknowledged?'✓ Your acknowledgement saved':'Acknowledgement pending'}</p>${!r.sent_by_me&&r.status==='pending'?`<button class="secondary" data-invite="${s(r.id)}" data-action="accept">I have read the expectations — accept visit</button><button class="secondary" data-invite="${s(r.id)}" data-action="decline">Decline visit</button>`:''}${r.status==='accepted'&&!r.my_acknowledged?`${r.expectation_flag==='intimacy_expected'?`<ul>${(d.guidance||[]).map(g=>`<li>${s(g)}</li>`).join('')}</ul>`:''}<button class="secondary" data-invite="${s(r.id)}" data-action="acknowledge" ${d.agreements?.home_invite?.mine?'':'disabled'}>I acknowledge the text and guidance above</button>`:''}${['accepted','pending','awaiting response'].includes(r.status)?`<button class="secondary" data-invite="${s(r.id)}" data-action="revoke">Cancel visit — no penalty</button>`:''}</div>`).join('')}</section>
 <section class="card"><details><summary>Talk about closeness and boundaries</summary><p>Optional questions. Answers here are shared with your partner only after both have answered or chosen not to answer.</p>${!d.next_level?.answers?.length?'<button class="secondary" id="open-next-level">Open optional conversation</button>':(d.next_level.questions||[]).map(q=>{const a=d.next_level.answers.find(a=>a.question_key===q.key)||{};return `<article class="conversation-question"><h3>${s(q.text)}</h3><div class="answer-columns"><form data-next="${s(q.key)}"><label>You<textarea name="answer" maxlength="4000" ${a.own_answer!=null?'disabled':''}>${s(a.own_answer||'')}</textarea></label>${a.own_answer==null?'<button class="secondary" name="choice" value="answer">Save answer</button><button class="secondary" name="choice" value="decline">Prefer not to answer</button>':'<p>✓ Your response is saved.</p>'}</form><div><h4>Your partner</h4><p>${a.revealed?s(a.partner_answer||'Chose not to answer.'):'Waiting for both responses before sharing.'}</p>${a.reluctance_reflection?`<p>${s(a.reluctance_reflection)}</p>`:''}</div></div></article>`;}).join('')}</details></section>
 <section class="card"><h2>Relationship conversation</h2><p>Choose relevant topics, add your own question, and answer independently through Guru.</p><button class="secondary" id="open-gate">Explore relationship readiness</button></section>`;
}
export function bind(root,ctx){
 const base=`/api/v1/lock-ins/${encodeURIComponent(ctx.data.lock_in_id)}`;
 root.querySelector('#after-refresh')?.addEventListener('click',()=>ctx.run(async()=>{ctx.patch(await ctx.session.get(base+'/after-date'));await ctx.refreshJourney();}));
 const post=async(path,body={})=>{ctx.patch(await ctx.session.post(base+path,body));await ctx.refreshJourney();};
 root.querySelectorAll('[data-agreement]').forEach(b=>b.addEventListener('click',()=>ctx.navigateTo('ceremony',{lockInId:ctx.data.lock_in_id,kind:b.dataset.agreement,returnTo:'after_date'})));
 root.querySelector('#open-next-level')?.addEventListener('click',()=>ctx.run(()=>post('/next-level')));
 root.querySelectorAll('[data-next]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();const declined=e.submitter.value==='decline',answer=new FormData(f).get('answer');ctx.run(()=>post('/next-level/answers',{question_key:f.dataset.next,declined,...(!declined?{answer_text:answer.trim()}:{})}));}));
 root.querySelector('#open-gate')?.addEventListener('click',()=>ctx.navigateTo('gate'));
 root.querySelector('#contact-request')?.addEventListener('submit',e=>{e.preventDefault();ctx.run(()=>post('/contact-requests',{channel:new FormData(e.target).get('channel')}));});
 root.querySelectorAll('[data-contact]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();const response=e.submitter.value,value=new FormData(f).get('contact_value');ctx.run(()=>post(`/contact-requests/${encodeURIComponent(f.dataset.contact)}/response`,{response,...(response==='accepted'&&value?{contact_value:value.trim()}:{})}));}));
 root.querySelector('#home-invite')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);ctx.run(()=>post('/home-invites',{request_id:crypto.randomUUID(),proposed_datetime:f.get('when'),expectation_flag:f.get('flag')}));});
 root.querySelectorAll('[data-invite]').forEach(b=>b.addEventListener('click',()=>ctx.run(async()=>{const path=`/home-invites/${encodeURIComponent(b.dataset.invite)}`;if(['accept','decline'].includes(b.dataset.action)){await ctx.session.post(base+path+'/see-flag',{});await post(path+'/respond',{response:b.dataset.action==='accept'?'accepted':'declined'});}else if(b.dataset.action==='acknowledge'){if(ctx.data.home_invites.find(r=>r.id===b.dataset.invite)?.expectation_flag==='intimacy_expected')await ctx.session.post(base+path+'/guidance',{});await post(path+'/acknowledge',{acknowledgement_version:ctx.data.invite_acknowledgement_version,acknowledged:true});}else await post(path+'/revoke');})));
}
