import { pairContext } from './pairContext.js';
const preferred=['relationship_meaning','exclusivity_check','timeline_expectation','open_question','disagreement_handling','money_talk'];
export function render(ctx) {
 const {data:d,safe:s}=ctx;
 if(!d)return '<h1>Relationship conversation</h1><p>Loading…</p>';
 const button=(action,label,disabled=false)=>`<button class="secondary" type="button" data-gate="${action}" ${disabled?'disabled':''}>${label}</button>`;
 let html=`<h1>Relationship conversation</h1><button class="secondary" id="gate-refresh">Refresh partner progress</button>${pairContext(ctx)}<p>Choose what matters to you. Both partners answer through Guru. Your written answers stay private; Guru currently compares selected options, not the meaning of free text.</p>`;
 if(!d.gate)return html+button('raise','Start the conversation');
 if(d.gate.status!=='open')return html+`<section class="card"><h2>${s(d.gate.status==='progressed'?'✓ Relationship started':'Conversation closed')}</h2><p>Your saved progress is preserved. Return Home to see your next step.</p></section>`;
 const asked=new Set((d.asked||[]).map(q=>q.key));
 const qs=(d.questions||[]).filter(q=>!asked.has(q.key));
 if(!d.my_questions_submitted)html+=`<section class="card"><h2>1. Choose up to three topics</h2><form id="gate-ask">${qs.filter(q=>preferred.includes(q.key)).map(q=>`<label class="checkbox-row"><input type="checkbox" name="question" value="${s(q.key)}">${s(q.text)}</label>`).join('')}<details><summary>More topics</summary>${qs.filter(q=>!preferred.includes(q.key)).map(q=>`<label class="checkbox-row"><input type="checkbox" name="question" value="${s(q.key)}">${s(q.text)}</label>`).join('')}</details><label>Add your own question (shared with your partner)<textarea name="custom" maxlength="300"></textarea></label><button class="secondary">Send topics to Guru</button></form></section>`;
 html+=`<section class="card"><h2>2. Both answer</h2><p>${s(d.report?.headline)}</p>${(d.asked||[]).map(q=>`<form data-answer="${s(q.key)}"><label>${s(q.prompt)}${q.kind==='scale'?`<select name="value" required><option value="">Choose…</option>${(q.options||[]).map(o=>`<option value="${s(o)}" ${d.my_answers?.[q.key]===o?'selected':''}>${s(o.replaceAll('_',' '))}</option>`).join('')}</select>`:`<textarea name="value" required maxlength="4000">${s(d.my_answers?.[q.key]||'')}</textarea>`}</label><p class="hint">${s(d.report?.lines?.find(l=>l.key===q.key)?.note||'Both partners answer this topic.')}</p><button class="secondary" ${d.gate.my_confirmed||d.gate.partner_confirmed?'disabled':''}>${d.my_answers?.[q.key]?'Update saved answer':'Save answer'}</button></form>`).join('')}</section>`;
 html+=`<section class="card"><h2>3. Reflect, then choose</h2><p>${s(d.reflection?.note)}</p>${d.reflection?.test_mode?`<p>Beta rehearsal: each partner explicitly finishes their reflection. This simulates the waiting interval only.</p><p>You: ${d.reflection.my_ready?'✓ Ready':'Not ready'} · Partner: ${d.reflection.partner_ready?'✓ Ready':'Waiting'}</p>${button('reflection-ready','I have reflected (test)',!d.report?.complete||d.reflection.my_ready)}`:''}<p>You: ${d.gate.my_confirmed?'✓ Confirmed':'Not confirmed'} · Partner: ${d.gate.partner_confirmed?'✓ Confirmed':'Waiting'}</p>${button('confirm','I want to move to Relationship',!d.may_confirm||d.gate.my_confirmed)}${button('decline','Stay in Dating')}</section>`;
 const pre=d.my_prerequisites||{};
 html+=`<section class="card"><h2>4. Readiness and agreement</h2><p>Your profile: ${pre.met?'✓ Complete':'Needs attention'} · Partner profile: ${d.partner_prerequisites_met?'✓ Complete':'Waiting'}</p>${!pre.vision_met?'<p>Add a Vision detail in your profile.</p>':''}<p>${s([...(pre.stats_missing||[]),...(pre.chemistry_missing||[])].map(k=>k.replaceAll('_',' ')).join(', '))}</p><button class="secondary" data-profile="dashboard">Review profile</button><button class="secondary" data-profile="boundaries">Review boundaries &amp; expectations</button><p>Exclusivity is a separate, explicit choice. Partner: ${d.gate.partner_exclusivity_ack?'✓ Acknowledged':'Waiting'}</p>${button('exclusivity-ack',d.gate.my_exclusivity_ack?'✓ Exclusivity acknowledged':'I acknowledge exclusivity',d.gate.my_exclusivity_ack)}<button class="secondary" id="entry-agreement" ${d.gate.my_confirmed&&d.gate.partner_confirmed?'':'disabled'}>${d.gate.my_entry_complete?'✓ Your agreement completed — review':'Review relationship agreement'}</button><p>Partner agreement: ${d.gate.partner_entry_complete?'✓ Complete':'Waiting'}</p>${button('enter-relationship','Enter Relationship',!d.gate.my_confirmed||!d.gate.partner_confirmed||!pre.met||!d.partner_prerequisites_met||!d.gate.my_entry_complete||!d.gate.partner_entry_complete||!d.gate.my_exclusivity_ack||!d.gate.partner_exclusivity_ack)}</section>`;
 return html;
}
export function bind(root,ctx){
 const base=`/api/v1/lock-ins/${encodeURIComponent(ctx.data.lock_in_id)}/gate`;
 root.querySelector('#gate-refresh')?.addEventListener('click',()=>ctx.run(async()=>{ctx.patch(await ctx.session.get(base));await ctx.refreshJourney();}));
 const act=async(action,body={})=>{const result=await ctx.session.post(`${base}/${action}`,{...(action==='raise'?{}:{round:ctx.data.gate.round}),...body});await ctx.refreshJourney();if(result.advanced)ctx.patch({...ctx.data,gate:{...ctx.data.gate,status:'progressed'}});else ctx.patch(result);};
 root.querySelectorAll('[data-gate]').forEach(b=>b.addEventListener('click',()=>ctx.run(()=>act(b.dataset.gate,b.dataset.gate==='exclusivity-ack'?{acknowledged:true}:{}))));
 root.querySelector('#gate-ask')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),custom=f.get('custom').trim();ctx.run(()=>act('ask',{question_keys:f.getAll('question'),...(custom?{custom_question:custom}:{})}));});
 root.querySelectorAll('[data-answer]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();const form=new FormData(f);ctx.run(()=>act('answer',{question_key:f.dataset.answer,value:form.get('value').trim()}));}));
 root.querySelector('#entry-agreement')?.addEventListener('click',()=>ctx.navigateTo('ceremony',{lockInId:ctx.data.lock_in_id,kind:'relationship_entry',returnTo:'gate'}));
 root.querySelectorAll('[data-profile]').forEach(b=>b.addEventListener('click',()=>ctx.navigateTo(b.dataset.profile)));
}
